package com.kmek.minecafe.item.custom;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.NotNull;

import java.util.List;

public class FortuneCookieItem extends Item {
    public FortuneCookieItem() {
        super(new Item.Properties().food(
                new FoodProperties.Builder()
                        .nutrition(3)
                        .saturationMod(1.5F)
                        .build()));
    }

    private final List<String> fortunes = List.of("Fortune will find you in the mines",
            "Crops will receive fine rain in the coming days",
            "Fine diamonds are in your future",
            "Buried treasure lies under the beach sands",
            "Lock your doors, for a creeper might be in your future",
            "Travel due north for new biomes",
            "Travel due south for new biomes",
            "Travel due east for new biomes",
            "Travel due west for new biomes",
            "Seek out the tallest tree for a fresh apple",
            "Dig straight down, you're onto something...",
            "Help!!! I'm trapped in a fortune cookie factory!!!",
            // Generated by ChatGPT
            "Your creativity and perseverance in will yield great rewards.",
            "Luck is on your side in your next adventure.",
            "The key to success in Minecraft is to always be prepared.",
            "A challenge you've been struggling with will soon be overcome.",
            "Don't be afraid to explore new territories, for they may hold great treasures.",
            "Your Minecraft building skills will be admired by many.",
            "Sometimes the greatest discoveries are found in the smallest details.",
            "Keep digging, for you never know what riches might be near.",
            "A project you've been putting off will be completed with ease.",
            "The secret to Minecraft success is teamwork and cooperation with others.",
            "A bountiful harvest awaits you in your farm, if you tend to it with care.",
            "Patience and diligence in farming will lead to great rewards.",
            "Your farm may face unexpected challenges, but with persistence, you will overcome them.",
            "Maintain balance by tending to your crops and animals alike.",
            "A well-planned farm can sustain you for a lifetime.",
            "A farm is not just a source of food, but a source of pride and accomplishment.",
            "Great riches are waiting for you in the depths of the world's caves.",
            "Every block you mine is a step closer to your next discovery.",
            "Remember to bring torches and a pickaxe on your next mining adventure.",
            "Your persistence in mining Minecraft's toughest ores will soon pay off.",
            "Don't be afraid to venture deeper in the mines.",
            "The greatest treasures lie in the darkest corners.",
            "The key to successful Minecraft mining is preparation and caution.",
            "Sometimes the most valuable discoveries are the ones you stumble upon by accident.",
            "Your mining skills will lead you to great success and fortune.",
            "Keep digging, for you never know what the underground may hold.",
            "Every failed mining attempt is a learning opportunity for the future."
    );

    private final List<ChatFormatting> colors = List.of(ChatFormatting.LIGHT_PURPLE,
            ChatFormatting.BLUE,
            ChatFormatting.DARK_PURPLE,
            ChatFormatting.GREEN,
            ChatFormatting.YELLOW
    );

    @Override
    public @NotNull ItemStack finishUsingItem(@NotNull ItemStack itemStack, @NotNull Level level, @NotNull LivingEntity livingEntity) {
        if (livingEntity instanceof Player player && !level.isClientSide) {
            ItemStack stack = new ItemStack(Items.PAPER);
            stack.setHoverName(Component
                    .literal(fortunes.get(level.random.nextInt(0, fortunes.size())))
                    .withStyle(colors.get(level.random.nextInt(0, colors.size()))));
            player.addItem(stack);
        }

        return livingEntity.eat(level, itemStack);
    }
}
